swagger: '2.0'
info:
  version: 1.0.0
  title: Simple Jokes API
  description: This is a simple Jokes API
  # put the contact info for your development or API team
  contact:
    email: you@your-company.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  
tags:
  - name: jokes
    description: Chuck norris jokes

paths:
  /jokes:
    get:
      summary: searches jokes
      operationId: searchJokes
      tags:
        - jokes
      description: 
        By passing in the appropriate options, you can search for
        available jokes
      produces:
      - application/json
      parameters:
      - in: query
        name: searchString
        description: pass an optional search string for looking up jokes with that text
        required: false
        type: string
      - in: query
        name: skip
        description: number of records to skip for pagination
        type: integer
        format: int32
        minimum: 0
      - in: query
        name: limit
        description: maximum number of records to return
        type: integer
        format: int32
        minimum: 0
        maximum: 50
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Joke'
        400:
          description: bad input parameter
    post:
      summary: adds a joke
      operationId: addJoke
      description: Adds a joke to the system
      tags:
        - jokes
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: joke
        description: Joke to add
        schema:
          $ref: '#/definitions/NewJoke'
      responses:
        201:
          description: joke created
        400:
          description: invalid input, object invalid
          
  /jokes/{jokeId}:
    get:
      summary: Get a Joke given its id
      description: Get a Joke given its id
      operationId: getJokeById
      tags:
        - jokes
      produces:
      - application/json
      parameters:
      - name: jokeId
        in: path
        description: ID of joke that to be fetched
        required: true
        type: string
        format: uuid
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Joke'
        400:
          description: Invalid ID supplied

        404:
          description: Joke not found
    delete:
      summary: Delete a joke by ID
      description: Delete a joke by ID
      operationId: deleteJoke
      tags:
        - jokes
      produces:
      - application/json
      parameters:
      - name: jokeId
        in: path
        description: ID of the joke to be deleted
        required: true
        type: string
        format: uuid
      responses:
        400:
          description: Invalid ID supplied
        404:
          description: Order not found
    put:
      summary: updates a joke
      operationId: updateJoke
      description: Updates a joke in the system
      tags:
        - jokes
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: jokeId
        in: path
        description: ID of the joke to be deleted
        required: true
        type: string
        format: uuid
      
      - in: body
        name: joke
        description: Joke to add
        schema:
          $ref: '#/definitions/Joke'
      responses:
        201:
          description: joke created
        400:
          description: invalid input, object invalid

definitions:
  Joke:
    type: object
    required:
    - id
    - uri
    - value
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      uri: 
        type: string
      value:
        type: string
        example: when Chuck Norris saw god it was like looking in the mirror
      categories:
        type: array
        items: 
          type: 'string'

  NewJoke:
    type: object
    required:
    - value
    properties:
      value:
        type: string
        example: when Chuck Norris saw god it was like looking in the mirror


# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /lfalcao-isel/ChelasJokesAPI/1.0.0
schemes:
 - http